### ISSUE TITLE
dialplan page is empty

### ISSUE THREAD

**Issue by prathibhacdac** [OpenSIPS/opensips-cp#284]
I'm using the latest version of opensips/control-panel from github. The dialplan page is blank. How to add a new dialplan?

**Comment by prathibhacdac** [comment]
How to include dialplan in the database table?

**Comment by umersaeedbajwa** [comment]
@prathibhacdac I am facing same issue. Are you able to resolve this?

**Comment by prathibhacdac** [comment]
Not resolved.

**Comment by umersaeedbajwa** [comment]
@prathibhacdac Any update. Are you able to resolve it yet ?

**Comment by umersaeedbajwa** [comment]
@prathibhacdac I am using openips 3.4 and opensips cp 9.3.4 which version you are using?

**Comment by umersaeedbajwa** [comment]
I see on console log receiving 500 from dialplan.php:1 . @bogdan-iancu Can you please check what is the issue. Am I missing any Configurations. Please guide me. 

![image](https://github.com/OpenSIPS/opensips-cp/assets/66518793/1e8c6ee7-6f14-4a36-a486-cccc59701d29)

**Comment by fdmgit** [comment]
I had the same issue with the Dialplan blank page (Error 500). 
I was using PHP 8.2. Now I downgraded to PHP 7.4 and the Dialplan page works. 
Looks like that not all parts of the Control Panel are ready for PHP 8.x

**Comment by Rico29** [comment]
hello
with php8.3, got this error :+1: 

`[Thu Jul 04 15:01:29.740346 2024] [php:error] [pid 3149953] [client xxx:47410] PHP Fatal error:  Uncaught Error: Attempt to assign property "dialplan" on null in /var/www/html/opensips-cp/config/tools/system/dialplan/settings.inc.php:24\nStack trace:\n#0 /var/www/html/opensips-cp/web/common/cfg_comm.php(230): require()\n#1 /var/www/html/opensips-cp/web/common/cfg_comm.php(398): get_params_from_tool()\n#2 /var/www/html/opensips-cp/web/common/cfg_comm.php(390): session_load_from_tool()\n#3 /var/www/html/opensips-cp/web/tools/system/dialplan/template/header.php(32): session_load()\n#4 /var/www/html/opensips-cp/web/tools/system/dialplan/dialplan.php(24): require('...')\n#5 {main}\n  thrown in /var/www/html/opensips-cp/config/tools/system/dialplan/settings.inc.php on line 24, referer: http://172.16.254.10/cp/menu.php
`

**Comment by Rico29** [comment]
see #297
