### ISSUE TITLE
Load_balancer option

### ISSUE THREAD

**Issue by inderjeetsharma** [OpenSIPS/opensips-cp#72]
Hello Team,

I;m getting below error while clicking show all/search in load_balancer  module.
OS: CentOS 7
Opensips:  3.0.1
Opensips-CP: 8

****PHP Fatal error:  Uncaught Error: [] operator not supported for strings in /var/www/html/opensips-cp/web/common/mi_comm.php:55\nStack trace:\n#0 /var/www/html/opensips-cp/web/common/mi_comm.php(87): write2json('lb_list', NULL, '127.0.0.1:8888/...', '')\n#1 /var/www/html/opensips-cp/web/tools/system/loadbalancer/template/loadbalancer.main.php(122): mi_command('lb_list', NULL, 'json:127.0.0.1:...', '')\n#2 /var/www/html/opensips-cp/web/tools/system/loadbalancer/loadbalancer.php(215): require('/var/www/html/o...')\n#3 {main}\n  thrown in /var/www/html/opensips-cp/web/common/mi_comm.php on line 55, referer: https://pbx815.therealpbx.com/opensips-cp/web/tools/system/loadbalancer/loadbalancer.php?action=search****

**Comment by bogdan-iancu** [comment]
Do you have the `load_balancer.so` module loaded in OpenSIPS ? are you sure you use the latest CP 8 from GIT ?
